---
# Setups node-docker image

- name: Set env vars
  environment:
      DOCKER_TIMEOUT: 10000
  shell: "echo $DOCKER_TIMEOUT"

# Okeanos images don't come with pip3
- name: Install "python3-pip" package
  apt:
    name: python3-pip
  become: true

- name: Install docker-py via pip
  pip:
    name: docker-py

- name: Install docker-compose via pip
  pip:
    name: docker-compose

- name: Install requests
  pip:
    name: requests
    version: 2.18.1
    state: forcereinstall

- name: Pull docker image
  docker_image:
    state: present
    timeout: 100000
    name: joenyland/express-hello-world

- name: start hello world
  docker_container:
    name: hello-world
    image: joenyland/express-hello-world
    ports:
      - "8080:8080"
