version: '3'
services:
  # front-end:
  #   build: './front-end'
  #   ports:
  #    - '4000:3000'
  nginx:
    container_name: npmminer_web
    image: npmminer_web
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./front-end/public:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"

