version: '3'
services:
  back-end:
    build:
      context: ./back-end
    volumes:
      - ./back-end:/app/
    ports:
      - '3000:3000'
  front-end:
    build:
      context: ./front-end
    volumes:
      - ./front-end:/app/
    ports:
      - '3001:3000'
    env_file:
      - ./dev.env
  nginx:
    image: nginx:alpine
    links:
      - front-end
    build:
      context: ./nginx
    ports:
      - "8080:80"

