version: '3'
services:
  back-end:
    build:
      context: ./backend
    volumes:
      - ./backend:/app/
    ports:
      - '3000:3000'
  front-end:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app/
    ports:
      - '3001:3000'
    environment:
      REACT_APP_GRAPHQL_SERVER_ADDRESS: 'http://npm-miner.com:3000/graphql'
      NODE_ENV: 'production'
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.prod/nginx.conf:/etc/nginx/conf.d/default.conf
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - "80:80"
    links:
      - front-end

