version: '3'
services:
  back-end:
    build:
      context: ./back-end
    volumes:
      - ./back-end:/app/
    ports:
      - '3000:3000'
  front-end:
    build:
      context: ./front-end
    volumes:
      - ./front-end:/app/
    ports:
      - '3001:3000'
    environment:
      REACT_APP_GRAPHQL_SERVER_ADDRESS: 'http://npm-miner.com:3000/graphql'
  nginx:
    image: nginx:alpine
    depends_on:
      - front-end
    build:
      context: ./nginx
    ports:
      - "80:80"

