# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/npm-miner

    steps:
      - checkout
      #- run: cd demo-server && npm install
      # run tests!
      #- run: cd demo-server && npm test
      - deploy:
          name: Deploy Using Ansible
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              # ansible npm-web -m ping -i /etc/ansible/hosts
              echo 'deploying'
            fi

